### ISSUE TITLE
Manifest Version 2 deprecated

### ISSUE THREAD

**Issue by tnutzmann** [53845714nF/CopyMaster#1]
Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

```JSON
{
	=="manifest_version": 2,==
	"name": "CopyMaster",
	"description" : "Allows copying to websites that want to prevent this.",
	"version": "1.0",
	"content_scripts": [
		{
		"matches": ["<all_urls>"],
		"js": ["Content.js"]
		}
	],
	"icons": {
          "256": "img/cm.png"
      }
}
```

**Comment by 53845714nF** [comment]
Kein Bock zu testen. Check mal ob es geht. Hab grade nur auf stackoverflow geguck was sich verändert hat. Wie es scheint nichts.

**Comment by 53845714nF** [comment]
Done
